name: Test release UI bundle

on:
  push:
    branches:
      - automate-ui-bundle

jobs:
  build_and_test:
    permissions:
      contents: read
      packages: write
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Create release
        run: npx gulp release
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_BRANCH: ${{ github.ref_name }}
